set(SUPPORTS_CXX "FALSE")
if("${COMPILER}" STREQUAL "intel")
  set(FFLAGS "-qno-opt-dynamic-align  -convert big_endian -assume byterecl -ftz -traceback -assume realloc_lhs -fp-model source")
  set(SUPPORTS_CXX "TRUE")
  set(CXX_LINKER "FORTRAN")
  set(FC_AUTO_R8 "-r8")
  set(FFLAGS_NOOPT "-O0")
  set(FIXEDFLAGS "-fixed")
  set(FREEFLAGS "-free")
endif()
set(MPICC "cc")
set(MPICXX "CC")
set(MPIFC "ftn")
set(SCC "cc")
set(SCXX "CC")
set(SFC "ftn")
set(CMAKE_OPTS "-DCMAKE_SYSTEM_NAME=Catamount")
set(PIO_FILESYSTEM_HINTS "lustre")
set(CFLAGS "-qno-opt-dynamic-align -fp-model precise -std=gnu99")
set(NETCDF_PATH "$ENV{NETCDF}")
set(PNETCDF_PATH "$ENV{PNETCDF}")
set(CPPDEFS "${CPPDEFS}  -DCESMCOUPLED")
set(CPPDEFS "${CPPDEFS}  -DLINUX")
set(SLIBS "${SLIBS}  -lnetcdff -lnetcdf")
if("${MODEL}" STREQUAL "pop")
  set(CPPDEFS "${CPPDEFS}  -D_USE_FLOW_CONTROL")
endif()
if("${MODEL}" STREQUAL "ufsatm")
  set(CPPDEFS "${CPPDEFS}  -DSPMD")
  set(FFLAGS "${FFLAGS}  $(FC_AUTO_R8)")
endif()
if("${MODEL}" STREQUAL "gptl")
  set(CPPDEFS "${CPPDEFS}  -DHAVE_NANOTIME -DBIT64 -DHAVE_VPRINTF -DHAVE_BACKTRACE -DHAVE_SLASHPROC -DHAVE_COMM_F2C -DHAVE_TIMES -DHAVE_GETTIMEOFDAY")
endif()
if("${MODEL}" STREQUAL "mom")
  set(FFLAGS "${FFLAGS}  $(FC_AUTO_R8) -Duse_LARGEFILE")
endif()
if("${MODEL}" STREQUAL "mpi-serial")
  set(CFLAGS "${CFLAGS}  -std=gnu89")
endif()
if("${COMPILER}" STREQUAL "intel")
  set(FFLAGS "${FFLAGS}  -march=core-avx2 -no-fma")
  set(CPPDEFS "${CPPDEFS}  -DFORTRANUNDERSCORE -DCPRINTEL")
  set(CFLAGS "${CFLAGS}  -march=core-avx2 -no-fma")
  if("${compile_threaded}" STREQUAL "TRUE")
    set(FFLAGS "${FFLAGS}  -qopenmp")
    set(CFLAGS "${CFLAGS}  -qopenmp")
  endif()
  if("${DEBUG}" STREQUAL "TRUE")
    set(FFLAGS "${FFLAGS}  -O0 -g -check uninit -check bounds -check pointers -fpe0 -check noarg_temp_created")
    set(CFLAGS "${CFLAGS}  -O0 -g")
  endif()
  if("${DEBUG}" STREQUAL "FALSE")
    set(FFLAGS "${FFLAGS}  -O2 -debug minimal")
    set(CFLAGS "${CFLAGS}  -O2 -debug minimal")
  endif()
  if("${MPILIB}" STREQUAL "mpich")
    set(SLIBS "${SLIBS}  -mkl=cluster")
  endif()
  if("${MPILIB}" STREQUAL "mpich2")
    set(SLIBS "${SLIBS}  -mkl=cluster")
  endif()
  if("${MPILIB}" STREQUAL "mvapich")
    set(SLIBS "${SLIBS}  -mkl=cluster")
  endif()
  if("${MPILIB}" STREQUAL "mvapich2")
    set(SLIBS "${SLIBS}  -mkl=cluster")
  endif()
  if("${MPILIB}" STREQUAL "mpt")
    set(SLIBS "${SLIBS}  -mkl=cluster")
  endif()
  if("${MPILIB}" STREQUAL "openmpi")
    set(SLIBS "${SLIBS}  -mkl=cluster")
  endif()
  if("${MPILIB}" STREQUAL "impi")
    set(SLIBS "${SLIBS}  -mkl=cluster")
  endif()
  if("${MPILIB}" STREQUAL "mpi-serial")
    set(SLIBS "${SLIBS}  -mkl")
  endif()
  if("${compile_threaded}" STREQUAL "TRUE")
    set(LDFLAGS "${LDFLAGS}  -qopenmp")
  endif()
endif()
if("${MODEL}" STREQUAL "ufsatm")
  set(INCLDIR "${INCLDIR}  -I$(EXEROOT)/atm/obj/FMS")
endif()
